# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"quote_sql_string": "00_core.ipynb",
         "get_sql_from_template": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://noklam.github.io/fast_jinjasql/"

git_url = "https://github.com/noklam/fast_jinjasql/tree/master/"

def custom_doc_links(name): return None
